### ISSUE TITLE
A simpler way

### ISSUE THREAD

**Issue by TanDuong986** [Helloiamwin/CRNN-with-captcha#1]
I wondering that why we don't use Pytesseract library to read this captcha ? When we are considering only this task. The area among the text is really clear so that it is more easy to convert to binary image and extract information with Pytesseract. That's just my narrow point of view to solve this intuitive problem. Is there any deeper meaning of this method that you used?

**Comment by Helloiamwin** [comment]
Hi DTan, 
Thanks for your response. You know I want to use the CRNN architecture to solve the unique characters such as handwriting, and captcha,... The captcha is easier than handwriting so this is a basic example before meeting handwriting that also is solved in my GitHub. You should read carefully this repository and move over the Handwriting issue.
